### PR TITLE
Declare codeowners for the fedora + konflux sig

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by arewm** [comment]
GitHub is reporting errors with this change:

> Unknown owner on line 5: make sure @gnaponie exists and has write access to the repository
…edora.md @ralphbean @gbenhaim @gnaponie @praiskup @tojaj
Unknown owner on line 5: make sure @praiskup exists and has write access to the repository
…ralphbean @gbenhaim @gnaponie @praiskup @tojaj
Unknown owner on line 5: make sure @tojaj exists and has write access to the repository
…@gbenhaim @gnaponie @praiskup @tojaj

**Comment by ralphbean** [comment]
@arewm any issue adding them with write access?

**Comment by arewm** [comment]
Would they just be granted access as outside collaborators or would you add them to the org itself?

**Comment by ralphbean** [comment]
I'm happy to add them to the org.

**Pull request merged**
