### PR TITLE
Propose code of conduct

### PR DESCRIPTION
**Pull request by ralphbean**
I think this is worth adopting. Let's not merge before circulating and making sure people are on board.

If you have objections to the spirit or the letter, speak up here!

### CODE REVIEW

**Review by scoheb — APPROVED** [review]

**Review by hugares — APPROVED** [review]

**Review by arewm — APPROVED** [review]

**Review by zregvart — APPROVED** [review]

**Review by yftacherzog — APPROVED** [review]

**Review by johnmcollier — APPROVED** [review]

**Review by eskultety — APPROVED** [review]
nitpicks:
- this should be IMO named CODE_OF_CONDUCT.md to remain consistent with the other repos under the https://github.com/konflux-ci org
- it should be linked from the main README (since we don't have a CONTRIBUTING document here)
- I haven't checked the rest of the repos in the org, but the code of conduct should be identical across the whole org, so unless it is this and all the COC documents should be unified.

**Review by gbenhaim — APPROVED** [review]

**Review by ifireball — APPROVED** [review]
While not really putting my lawyer hat on, and not dwelling too much on the fine print, this does LGTM.

**Comment by ralphbean** [comment]
> nitpicks:
> 
> * this should be IMO named CODE_OF_CONDUCT.md to remain consistent with the other repos under the https://github.com/konflux-ci org
Will do.
> * it should be linked from the main README (since we don't have a CONTRIBUTING document here)
Can do. I think github automatically shows it linked in the UI near the top of the main repo UI though.
> * I haven't checked the rest of the repos in the org, but the code of conduct should be identical across the whole org, so unless it is this and all the COC documents should be unified.
Let's try putting a copy in https://github.com/konflux-ci/.github to see if it applies across the org.

**Review by dirgim — APPROVED** [review]

**Review by elsony — APPROVED** [review]

**Review by happybhati — APPROVED** [review]
LGTM!

**Comment by ralphbean** [comment]
Thanks all!

**Comment by ralphbean** [comment]
(Will follow up to rename it to all caps to match the conventional style; and try adding a copy to the .github repo.

**Pull request merged**
